version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - npm-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}
